### PR TITLE
Ezekiel

### PR DESCRIPTION
**Pull request by BSU-EzekielHolmes**
I added a Kotlin program to the introductory example 4 placeholder. It's a summation program that prints the sum of the values in an array.

### CODE REVIEW

**Review by samfarmer1 — APPROVED** [review]
Looks good!

**Comment by BSU-EzekielHolmes** [comment]
Instead of leaving my code in plain text on the website, I just provided links in index.html to a couple of files I recently added to the repository. I think it makes formatting easier, it resolves my tabbing issues and this way I can demonstrate the code easily during presentation if asked to.

**Comment by BSU-EzekielHolmes** [comment]
Instead of leaving my code in plain text on the website, I just provided links in index.html to a couple of files I recently added to the repository. I think it makes formatting easier, it resolves my tabbing issues and this way I can demonstrate the code easily during presentation if asked to.
I see Samantha approved my changes already but that was before I made a few changes. I believe the changes are finalized now and would like for at least one other person to take a look at the changes I've made before I merge them. Otherwise I'll merge by about 4:00 P.M. tomorrow.

**Review by samfarmer1 — APPROVED** [review]

**Comment by BWilson191** [comment]
sweet

**Pull request merged**
